/*
  DhanDiary - Improved Database Schema for NeonDB (PostgreSQL)
  
  Run this script in your Neon SQL Editor to initialize or reset your database.
  WARNING: This will define the structure for a fresh database.
*/

-- Enable UUID extension for unique IDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE
-- Stores authentication details and profile info
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_login TIMESTAMPTZ,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted')),
    clerk_id TEXT UNIQUE -- Link to Clerk Authentication
);

-- Index for fast Clerk lookups
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_clerk_id ON users(clerk_id);

-- 2. ENTRIES TABLE (cash_entries)
-- Stores the actual transaction data
-- Using 'cash_entries' as the table name based on existing code references
CREATE TABLE IF NOT EXISTS cash_entries (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- Internal Server ID for indexing
    client_id TEXT UNIQUE NOT NULL, -- The UUID generated by the app (offline-first support)
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- Transaction Details
    type TEXT CHECK (type IN ('in', 'out')),
    amount NUMERIC(15, 2) NOT NULL,
    category TEXT NOT NULL,
    note TEXT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    currency TEXT DEFAULT 'INR',
    
    -- Sync & Versioning Fields
    server_version INTEGER DEFAULT 1, -- Increments on update for conflict resolution
    deleted BOOLEAN DEFAULT FALSE,   -- Soft delete support
    need_sync BOOLEAN DEFAULT FALSE, -- Compatibility with sync logic
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SUMMARIES TABLE (For Performance)
-- Pre-computed daily totals to avoid expensive aggregation queries on mobile
CREATE TABLE IF NOT EXISTS daily_summaries (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    
    total_in NUMERIC(15, 2) DEFAULT 0,
    total_out NUMERIC(15, 2) DEFAULT 0,
    count INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(user_id, date) -- One summary per user per day
);

-- 4. INDEXES (Performance Optimization)
CREATE INDEX IF NOT EXISTS idx_entries_user_date ON cash_entries(user_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_entries_updated_at ON cash_entries(updated_at);
-- client_id is already unique index
CREATE INDEX IF NOT EXISTS idx_summaries_user_date ON daily_summaries(user_id, date);

-- 5. AUTOMATIC TIMESTAMP UPDATER
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply triggers
DROP TRIGGER IF EXISTS update_users_modtime ON users;
CREATE TRIGGER update_users_modtime
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_entries_modtime ON cash_entries;
CREATE TRIGGER update_entries_modtime
    BEFORE UPDATE ON cash_entries
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- 6. VERSION INCREMENTER (For Sync)
CREATE OR REPLACE FUNCTION increment_server_version()
RETURNS TRIGGER AS $$
BEGIN
    NEW.server_version = COALESCE(OLD.server_version, 0) + 1;
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS increment_entry_version ON cash_entries;
CREATE TRIGGER increment_entry_version
    BEFORE UPDATE ON cash_entries
    FOR EACH ROW
    EXECUTE FUNCTION increment_server_version();
